[14.0][FIX] account fiscal year fix upgrade
error upgrading module
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "date_range_type_date_range_type_uniq"
DETAIL:  Key (name, company_id)=(Fiscal Year, 1) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo-dev/odoo-dev14/OCB/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo-dev/odoo-dev14/OCA/account-financial-tools/account_fiscal_year/data/date_range_type.xml:3, near
<record id="fiscalyear" model="date.range.type">
        <field name="name">Fiscal Year</field>
        <field name="allow_overlap" eval="False"/>
    </record>