[FIX] account_invoice_currency: Integration tests
Creating a partner in at install mode raises this in integration environment:

    IntegrityError: null value in column "sale_warn" violates not-null constraint

Moving to post install mode.