Fix frozendict error on context mutations
The context is no longer mutable in the V8 API, and when calling
V7 API methods from V8 API methods will result in an error:
NotImplementedError: '__setitem__' not supported on frozendict

To work around this, copy the context prior to mutation. See also
Xavier Morel's answer on https://github.com/odoo/odoo/issues/4333
which confirms this.